# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-31 09:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='flashcards',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cards.Flashcard'),
        ),
    ]
